import { storage } from "../../../storage";
import type { InsertDream, InsertDejavuEntry } from "@shared/schema";

const SEED_DREAMS: Omit<InsertDream, 'embedding'>[] = [
  {
    title: "Denizde Boğulma",
    description: "Mavi, derin bir denizde yüzüyordum. Birden ayaklarım ağırlaştı ve suya battım. Nefes almaya çalışırken panik yaşadım. Uzaktan birinin bana seslendiğini duydum ama kim olduğunu göremedim.",
    location: "dogal",
    emotion: "korkulu",
    themes: ["su", "tehlike", "kaybolma"],
    objects: ["deniz", "dalga", "karanlık"],
    intensity: 9,
    dreamDate: new Date("2024-11-15"),
  },
  {
    title: "Sınav Kabusu",
    description: "Üniversite sınavına girdim ama hiçbir soruyu bilmiyordum. Saat hızla ilerliyordu ve ben sadece boş kağıda bakıyordum. Öğretmen sürekli bana bakıyordu. Ter içinde uyandım.",
    location: "okul",
    emotion: "endiseli",
    themes: ["başarısızlık", "zaman", "stres"],
    objects: ["kalem", "kağıt", "saat"],
    intensity: 8,
    dreamDate: new Date("2024-11-18"),
  },
  {
    title: "Uçuş Rüyası",
    description: "Çatıdan atladım ve uçmaya başladım. İstanbul'un üzerinde süzülüyordum. Boğaz köprüsünü gördüm, martılarla birlikte uçtum. Özgür ve mutlu hissettim.",
    location: "dogal",
    emotion: "mutlu",
    themes: ["özgürlük", "yükseklik", "keşif"],
    objects: ["gökyüzü", "bulut", "kuş"],
    intensity: 7,
    dreamDate: new Date("2024-11-20"),
  },
  {
    title: "Kayıp Çocuk",
    description: "Kalabalık bir AVM'de küçük kardeşimi kaybettim. Her yerde onu arıyordum ama bulamıyordum. İnsanlar bana yardım etmiyordu. Sonunda onu bir oyuncakçıda buldum.",
    location: "sehir",
    emotion: "endiseli",
    themes: ["kaybolma", "aile", "koruma"],
    objects: ["merdiven", "insan", "oyuncak"],
    intensity: 8,
    dreamDate: new Date("2024-11-22"),
  },
  {
    title: "Düğün Günü",
    description: "Kendi düğünümde gelinlik giymiştim. Salon çiçeklerle doluydu. Ailem ve arkadaşlarım oradaydı. Müzik çalıyordu ve dans ediyorduk. Çok mutlu ve huzurluydum.",
    location: "ev",
    emotion: "mutlu",
    themes: ["kutlama", "aile", "sevgi"],
    objects: ["çiçek", "müzik", "elbise"],
    intensity: 6,
    dreamDate: new Date("2024-11-25"),
  },
  {
    title: "Eski Okul",
    description: "İlkokul binasına geri döndüm. Her şey eskisi gibiydi ama ben yetişkin boyutundaydım. Sıralar küçük görünüyordu. Eski öğretmenim sınıfa girdi ve bana gülümsedi.",
    location: "okul",
    emotion: "saskin",
    themes: ["geçmiş", "nostalji", "değişim"],
    objects: ["sıra", "tahta", "zil"],
    intensity: 5,
    dreamDate: new Date("2024-11-28"),
  },
  {
    title: "Metro Yolculuğu",
    description: "Bilinmeyen bir metro hattındaydım. Her durakta garip insanlar biniyordu. Nereye gittiğimi bilmiyordum. Tünel karanlıktı ve tren hızlanıyordu. Son durakta ışık gördüm.",
    location: "sehir",
    emotion: "merakli",
    themes: ["yolculuk", "bilinmeyen", "geçiş"],
    objects: ["tren", "tünel", "ışık"],
    intensity: 6,
    dreamDate: new Date("2024-12-01"),
  },
  {
    title: "Anneannemin Evi",
    description: "Anneannemin köydeki evine gittim. O çoktan vefat etmişti ama rüyamda oradaydı. Bana çay ikram etti ve sohbet ettik. Sarıldık. Uyandığımda yanaklarım ıslaktı.",
    location: "ev",
    emotion: "huzunlu",
    themes: ["aile", "kayıp", "özlem"],
    objects: ["çay", "soba", "fotoğraf"],
    intensity: 9,
    dreamDate: new Date("2024-12-03"),
  },
  {
    title: "Karanlık Figür",
    description: "Yatak odamda siyah bir gölge vardı. Hareket etmiyordu ama beni izliyordu. Bağırmak istedim ama sesim çıkmadı. Yavaşça bana yaklaştı. Ter içinde uyandım.",
    location: "ev",
    emotion: "korkulu",
    themes: ["tehlike", "bilinmeyen", "güvensizlik"],
    objects: ["gölge", "yatak", "karanlık"],
    intensity: 10,
    dreamDate: new Date("2024-12-05"),
  },
  {
    title: "Orman Gezisi",
    description: "Yeşil, büyülü bir ormanda yürüyordum. Ağaçlar dev gibiydi. Kuş sesleri her yerdeydi. Bir geyik gördüm, bana baktı ve koşmaya başladı. Onu takip ettim.",
    location: "dogal",
    emotion: "merakli",
    themes: ["doğa", "keşif", "huzur"],
    objects: ["ağaç", "geyik", "yaprak"],
    intensity: 5,
    dreamDate: new Date("2024-12-07"),
  },
  {
    title: "İş Toplantısı Felaketi",
    description: "Önemli bir sunumda pantolonumu unuttum. Herkes bana bakıyordu ve gülüyordu. Kaçmak istedim ama kapılar kilitliydi. Patronum başını salladı.",
    location: "is",
    emotion: "saskin",
    themes: ["utanç", "başarısızlık", "kontrol kaybı"],
    objects: ["masa", "projeksiyon", "kravat"],
    intensity: 8,
    dreamDate: new Date("2024-12-08"),
  },
  {
    title: "Yıldızlı Gece",
    description: "Uzayda süzülüyordum. Gezegenler etrafımda dönüyordu. Yıldızlara dokunabiliyordum. Sonsuzluk hissettim. Dünya uzaktan mavi bir bilye gibi görünüyordu.",
    location: "dogal",
    emotion: "huzurlu",
    themes: ["sonsuzluk", "keşif", "özgürlük"],
    objects: ["yıldız", "gezegen", "uzay"],
    intensity: 7,
    dreamDate: new Date("2024-12-09"),
  },
  {
    title: "Eski Sevgili",
    description: "Yıllar önce ayrıldığım sevgilimle bir kafede oturuyorduk. Her şey eskisi gibiydi. Gülüştük, konuştuk. Sonra bana 'gitmeliyim' dedi ve kayboldu.",
    location: "sehir",
    emotion: "huzunlu",
    themes: ["geçmiş", "kayıp", "nostalji"],
    objects: ["kahve", "masa", "pencere"],
    intensity: 7,
    dreamDate: new Date("2024-12-10"),
  },
  {
    title: "Tsunami Dalgası",
    description: "Sahilde duruyordum. Deniz çekildi ve sonra devasa bir dalga geldi. Koşmaya çalıştım ama ayaklarım çamura batıyordu. Dalga her şeyi yuttu.",
    location: "dogal",
    emotion: "korkulu",
    themes: ["su", "tehlike", "güçsüzlük"],
    objects: ["dalga", "kum", "su"],
    intensity: 10,
    dreamDate: new Date("2024-12-11"),
  },
  {
    title: "Bebek Doğumu",
    description: "Hastanede bir bebek doğurdum. Onu kucağıma aldım ve ağladım. Küçücük elleri vardı. Ona isim vermeye çalıştım ama hatırlayamadım.",
    location: "hastane",
    emotion: "mutlu",
    themes: ["doğum", "yeni başlangıç", "sorumluluk"],
    objects: ["bebek", "hastane", "yastık"],
    intensity: 8,
    dreamDate: new Date("2024-12-12"),
  },
  {
    title: "Terkedilmiş Ev",
    description: "Büyük, eski ve terkedilmiş bir evdeydim. Duvarlar çatlaktı. Birisi beni takip ediyordu ama kim olduğunu göremiyordum. Merdivenlerde ayak sesleri duydum.",
    location: "ev",
    emotion: "korkulu",
    themes: ["tehlike", "bilinmeyen", "geçmiş"],
    objects: ["merdiven", "kapı", "toz"],
    intensity: 9,
    dreamDate: new Date("2024-12-13"),
  },
  {
    title: "Köpekle Koşu",
    description: "Sahilde köpeğimle koşuyordum. Güneş batıyordu ve deniz parlıyordu. Köpeğim mutluydu ve kuyruk sallıyordu. Huzur doluydu her şey.",
    location: "dogal",
    emotion: "huzurlu",
    themes: ["doğa", "dostluk", "özgürlük"],
    objects: ["köpek", "sahil", "güneş"],
    intensity: 4,
    dreamDate: new Date("2024-12-14"),
  },
  {
    title: "Gizli Oda",
    description: "Evimde hiç bilmediğim gizli bir oda keşfettim. İçi eski eşyalarla doluydu. Bir kutu buldum, içinde eski mektuplar vardı. Hepsi benim için yazılmıştı.",
    location: "ev",
    emotion: "merakli",
    themes: ["keşif", "sır", "geçmiş"],
    objects: ["kutu", "mektup", "anahtar"],
    intensity: 6,
    dreamDate: new Date("2024-12-15"),
  },
  {
    title: "Konser Sahnesi",
    description: "Binlerce kişinin önünde sahneye çıktım. Şarkı söyledim ve herkes alkışladı. Işıklar gözümü alıyordu. Kendimi yıldız gibi hissettim.",
    location: "diger",
    emotion: "mutlu",
    themes: ["başarı", "tanınma", "özgüven"],
    objects: ["mikrofon", "ışık", "sahne"],
    intensity: 7,
    dreamDate: new Date("2024-12-16"),
  },
  {
    title: "Labirent",
    description: "Yeşil çitlerden oluşan devasa bir labirentte kayboldum. Her köşede çıkmaz sokak vardı. Yukarıdan bir ses bana yol gösterdi ama anlayamadım.",
    location: "dogal",
    emotion: "endiseli",
    themes: ["kaybolma", "arayış", "kararsızlık"],
    objects: ["çit", "yol", "gökyüzü"],
    intensity: 7,
    dreamDate: new Date("2024-12-17"),
  },
  {
    title: "Yağmurda Yürüyüş",
    description: "Şehrin ortasında yağmurda yürüyordum. Şemsiyem yoktu ama umursamadım. Islak sokaklarda ayak izlerim kayboluyordu. Huzurluydum.",
    location: "sehir",
    emotion: "huzurlu",
    themes: ["su", "huzur", "yalnızlık"],
    objects: ["yağmur", "sokak", "ışık"],
    intensity: 4,
    dreamDate: new Date("2024-12-18"),
  },
  {
    title: "Uçak Düşmesi",
    description: "Uçaktaydım ve türbülans başladı. Uçak kontrolden çıktı ve yere doğru düşmeye başladı. Panik içinde bağırdım. Yere çarpmadan önce uyandım.",
    location: "diger",
    emotion: "korkulu",
    themes: ["tehlike", "kontrolsüzlük", "ölüm korkusu"],
    objects: ["uçak", "bulut", "kemer"],
    intensity: 10,
    dreamDate: new Date("2024-12-19"),
  },
  {
    title: "Çocukluk Arkadaşı",
    description: "Çocukluk arkadaşımla parkta oynadık. Her şey eskisi gibiydi. Top oynadık, ağaca çıktık. Güneş batarken eve döndük. Yolda konuştuk.",
    location: "dogal",
    emotion: "mutlu",
    themes: ["geçmiş", "dostluk", "nostalji"],
    objects: ["top", "ağaç", "park"],
    intensity: 5,
    dreamDate: new Date("2024-12-20"),
  },
  {
    title: "Ayna Yansıması",
    description: "Aynaya baktım ama yansımam farklıydı. Daha yaşlı ve yorgun görünüyordum. Yansımam benimle konuştu ve 'dikkatli ol' dedi. Korkuyla geri çekildim.",
    location: "ev",
    emotion: "saskin",
    themes: ["kimlik", "bilinmeyen", "uyarı"],
    objects: ["ayna", "yüz", "ışık"],
    intensity: 8,
    dreamDate: new Date("2024-12-21"),
  },
];

const SEED_DEJAVUS: Omit<InsertDejavuEntry, 'embedding'>[] = [
  {
    description: "Deniz kenarında dururken bir dalganın geldiğini gördüm. Bu anı daha önce yaşamış gibi hissettim. Tam olarak ne zaman bilmiyorum ama çok tanıdık geldi.",
    location: "dogal",
    emotion: "saskin",
    familiarity: 8,
    triggerContext: "Tatilde denize girerken dalga geldiğinde tetiklendi",
    entryDate: new Date("2024-11-20"),
  },
  {
    description: "Bir kafede otururken pencereden dışarı baktım. Caddenin görüntüsü, ışık açısı, her şey bir rüyadan tanıdık geldi. Sanki bunu daha önce yaşamıştım.",
    location: "sehir",
    emotion: "merakli",
    familiarity: 7,
    triggerContext: "Yeni açılan kafeye ilk kez gittiğimde",
    entryDate: new Date("2024-11-25"),
  },
  {
    description: "Anneannemi rüyamda görmüştüm. Ertesi gün eski fotoğraflarına bakarken aynı sahneyi hatırladım. Çay içerken çekilmiş bir fotoğraftı.",
    location: "ev",
    emotion: "huzunlu",
    familiarity: 9,
    triggerContext: "Eski aile albümünü karıştırırken",
    entryDate: new Date("2024-12-04"),
  },
  {
    description: "Metroda seyahat ederken tünel karanlığına daldık. O an bir rüyayı hatırladım, aynen böyle bir tünel geçişi vardı. Tüylerim diken diken oldu.",
    location: "sehir",
    emotion: "saskin",
    familiarity: 8,
    triggerContext: "Akşam işten eve dönerken metroda",
    entryDate: new Date("2024-12-02"),
  },
  {
    description: "Yağmurda yürürken sokaklara baktım. Her şey çok tanıdık geldi. Islak asfalt, yansımalar, sessizlik. Sanki bunu daha önce yaşamıştım, belki bir rüyada.",
    location: "sehir",
    emotion: "huzurlu",
    familiarity: 6,
    triggerContext: "Akşam yağmurunda yürürken",
    entryDate: new Date("2024-12-19"),
  },
  {
    description: "İş toplantısında patronumun yüz ifadesini görünce dondum. Bu anı daha önce görmüştüm. Tam olarak ne diyeceğini bile biliyordum gibiydim.",
    location: "is",
    emotion: "endiseli",
    familiarity: 7,
    triggerContext: "Haftalık departman toplantısında",
    entryDate: new Date("2024-12-09"),
  },
  {
    description: "Eski okul binamın önünden geçtim. İçeri baktığımda her şey tanıdık geldi ama farklıydı. Sanki bu anı daha önce bir rüyada yaşamıştım.",
    location: "okul",
    emotion: "saskin",
    familiarity: 8,
    triggerContext: "Mahalleden geçerken okulumu görünce",
    entryDate: new Date("2024-11-29"),
  },
  {
    description: "Gece yatarken odamda bir gölge gördüm. Kalp atışlarım hızlandı. Bu anı daha önce yaşamış gibiydim. Bir rüyada belki.",
    location: "ev",
    emotion: "korkulu",
    familiarity: 9,
    triggerContext: "Gece lambaları kapatınca",
    entryDate: new Date("2024-12-06"),
  },
  {
    description: "Parkta yürürken bir geyik gördüm. Aniden bir rüya hatırladım, ormanda geyik takip ediyordum. Aynı bakış, aynı duruş.",
    location: "dogal",
    emotion: "merakli",
    familiarity: 7,
    triggerContext: "Hafta sonu parkta yürüyüş yaparken",
    entryDate: new Date("2024-12-08"),
  },
  {
    description: "Uçak kalkarken türbülansa girdi. O an bir panik hissettim ve bir rüyayı hatırladım. Uçakla ilgili korkutucu bir rüya görmüştüm.",
    location: "diger",
    emotion: "korkulu",
    familiarity: 8,
    triggerContext: "İstanbul-Ankara uçuşunda kalkışta",
    entryDate: new Date("2024-12-20"),
  },
  {
    description: "Eski bir evde gizli bir oda buldum. İçinde eski eşyalar vardı. Bu sahneyi daha önce yaşamış gibiydim, belki bir rüyada gördüm.",
    location: "ev",
    emotion: "merakli",
    familiarity: 9,
    triggerContext: "Taşındığımız yeni evde keşif yaparken",
    entryDate: new Date("2024-12-16"),
  },
  {
    description: "Bir düğüne gittim. Salon çiçeklerle doluydu ve müzik çalıyordu. Bu anı daha önce yaşamış gibi hissettim. Bir rüyadan mı hatırlıyorum?",
    location: "diger",
    emotion: "mutlu",
    familiarity: 6,
    triggerContext: "Kuzenimin düğününde",
    entryDate: new Date("2024-11-26"),
  },
  {
    description: "Aynaya bakarken yansımam bir anlığına farklı göründü. Daha yorgun, daha yaşlı. Bir rüya hatırladım, aynada konuşan ben.",
    location: "ev",
    emotion: "saskin",
    familiarity: 8,
    triggerContext: "Sabah banyoda yüzümü yıkarken",
    entryDate: new Date("2024-12-22"),
  },
  {
    description: "Yıldızlara bakarken sonsuzluk hissettim. Bir rüya geldi aklıma, uzayda süzülüyordum. Aynı his, aynı büyülenme.",
    location: "dogal",
    emotion: "huzurlu",
    familiarity: 7,
    triggerContext: "Gece balkondan gökyüzüne bakarken",
    entryDate: new Date("2024-12-10"),
  },
  {
    description: "AVM'de kalabalıkta yürürken bir çocuğun kaybolduğunu duydum. O an bir rüya hatırladım, kardeşimi arıyordum. Tüylerim diken diken oldu.",
    location: "sehir",
    emotion: "endiseli",
    familiarity: 8,
    triggerContext: "Hafta sonu alışverişe çıktığımda",
    entryDate: new Date("2024-11-23"),
  },
  {
    description: "Labirent gibi bir bahçede yürüdüm. Çitler arasında kayboldum. Bir rüyayı hatırladım, aynı yeşil labirent. Çıkış bulamıyordum.",
    location: "dogal",
    emotion: "saskin",
    familiarity: 8,
    triggerContext: "Botanik bahçesini ziyaret ederken",
    entryDate: new Date("2024-12-18"),
  },
];

export async function seedDreamData(): Promise<{ dreams: number; dejavus: number }> {
  console.log("🌙 Starting dream data seeding...");
  
  let dreamCount = 0;
  let dejavuCount = 0;
  
  for (const dream of SEED_DREAMS) {
    try {
      await storage.createDream(dream);
      dreamCount++;
      console.log(`✓ Created dream: ${dream.title}`);
    } catch (error) {
      console.error(`✗ Failed to create dream: ${dream.title}`, error);
    }
  }
  
  for (const dejavu of SEED_DEJAVUS) {
    try {
      await storage.createDejavuEntry(dejavu);
      dejavuCount++;
      console.log(`✓ Created dejavu entry`);
    } catch (error) {
      console.error(`✗ Failed to create dejavu entry`, error);
    }
  }
  
  console.log(`\n🎉 Seeding complete: ${dreamCount} dreams, ${dejavuCount} dejavu entries`);
  return { dreams: dreamCount, dejavus: dejavuCount };
}
